services:
  mtgosdk:
    image: videreproject/mtgosdk:headless
    container_name: mtgosdk
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=:99
      - WINEDEBUG=-all
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["/bin/bash"]
