/** @file
  Copyright (c) 2024, Cory Bennett. All rights reserved.
  SPDX-License-Identifier: Apache-2.0
**/


namespace MTGOSDK.Core.Reflection.Attributes;

/// <summary>
/// Source-generated attribute indicating the remote @base access path.
/// </summary>
/// <remarks>
/// This attribute is generated by the RemoteAccessPathGenerator source generator
/// to mark properties that access remote object members. The path represents
/// the member access chain (e.g., "Rarity.Name" for @base.Rarity.Name).
/// </remarks>
[AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
public sealed class RemoteAccessPathAttribute : Attribute
{
  /// <summary>
  /// The remote member access path (e.g., "ConvertedManaCost", "Rarity.Name").
  /// </summary>
  public string Path { get; }

  /// <summary>
  /// Whether the access uses Unbind(this) or Unbind(@base) instead of @base.
  /// </summary>
  public bool UsesUnbind { get; }

  /// <summary>
  /// Whether the path is known to return a primitive type at compile time.
  /// </summary>
  public bool IsPrimitive { get; }

  public RemoteAccessPathAttribute(
    string path,
    bool usesUnbind = false,
    bool isPrimitive = false)
  {
    Path = path;
    UsesUnbind = usesUnbind;
    IsPrimitive = isPrimitive;
  }
}
